### PR TITLE
Added 2 new features

### PR DESCRIPTION
**Pull request by CanYouJustWorkPlease**
Added 2 new features as options: "Paragraph and two new lines" and "Paragraph, two new lines and separator".

### CODE REVIEW

**Comment by Scruffy21** [comment]
Would it make sense to use `+` instead of `*` in the regexForSymbolsAdvanced?
So that it does not create a paragraph on just 3 dots `...`
`/((?:[\.\?\!][^\.\?\!]+){2})([\.\?\!])[\s\n]/g;` instead of `/((?:[\.\?\!][^\.\?\!]*){2})([\.\?\!])[\s\n]/g;`

[regex link](https://regex101.com/r/RneYPQ/1)

**Comment by CanYouJustWorkPlease** [comment]
Hmm. Why not keep both of them as 2 separate options and add a tooltip next to each option that shows how each option works? So, "Paragraph and two new lines" will have 2 options and "Paragraph, two new lines and separator" will have 2 options, as well.

**Comment by CanYouJustWorkPlease** [comment]
I forgot to mention, if you're down for this, I could implement it.

**Comment by Scruffy21** [comment]
It's up to @JeffKang. Personally, I think that would just clutter the options unnecessarily. Too many options may be confusing for users.

**Comment by CanYouJustWorkPlease** [comment]
I don't mind clutter as long as I get more functionality.

Ok, then it's up to him.

**Comment by JeffKang** [comment]
Hi, yes let's just keep one version of the two new options. Having two versions of an option is a bit too much at this point, thanks.

**Comment by CanYouJustWorkPlease** [comment]
I proposed to Jeff to revert the code to your own version, since my code has issues that I will have to address, which I don't know when it will happen.

**Pull request merged**
